server:
  port: 8083
  servlet:
    context-path: /ddd

springdoc:
  swagger-ui:
    # API 排序
    tags-sorter: alpha
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${"MYSQL_DATABASE":ddd}?autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  # redis 单机模式
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  session:
    redis:
      configure-action: none
      namespace: RT-USERCENTER
    store-type: redis

  mvp:
    log-request-details: true

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml


# log
logging:
  level:
    root: info
    org:
      springframework:
        web: debug
    sun:
      rmi: info
    com:
      mqm: debug



